name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - .eslintignore
      - .eslintrc.json
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md
      - tsconfig.json
      - tsconfig.build.json
      - .github/workflows/docs.yml
      - "docs/**"
    tags-ignore:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

      - name: Verify build
        run: pnpm run build

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npx \
          -p @semantic-release/npm \
          -p @semantic-release/exec \
          -p @semantic-release/git \
          -p @semantic-release/commit-analyzer \
          -p @semantic-release/release-notes-generator \
          -p @semantic-release/github \
          -p @semantic-release/changelog \
          -p conventional-changelog-conventionalcommits \
          -p genversion \
          semantic-release
